name: ci-golang-quality-workflow
on: [push, pull_request]

jobs:
  quality-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
